### ISSUE TITLE
1.1.1 Doesn't work with Vaadin 22.0.1

### ISSUE THREAD

**Issue by mvysny** [vaadin-component-factory/multiple-select#9]
Hi, thank you so much for your work! Unfortunately the component doesn't work with Vaadin 22.0.1 and fails in runtime with Java exception:
```
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:484)
	... 55 more
Caused by: java.lang.NoClassDefFoundError: com/vaadin/flow/data/binder/HasItemsAndComponents$ItemComponent
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2432)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:864)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187)
	at org.vaadin.example.MainView.<init>(MainView.java:20)
	... 60 more
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.data.binder.HasItemsAndComponents$ItemComponent
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187)
	... 68 more
```

Probably because `ItemComponent` has been moved to `HasItemComponents` and thus this addon just needs to be recompiled and re-released.

**Comment by mvysny** [comment]
Damn! Fooled by stupid Vaadin Directory version selector which places version 1.1.1 above 3.0.1. Sorry, nevermind :)
